name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3 # Poetryのバージョン

    - name: Install dependencies
      run: poetry install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      env:
        LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
      run: |
        #poetry build  #  deploy lambda, so don't use poetry build
        poetry export --format requirements.txt --without-hashes > requirements.txt #  export dependencies from poetry
        pip install -r feedparser --target rss_aws_whatsnew/package # import dependencies
        cd rss_aws_whatsnew
        zip -r ../deploy.zip .
        cd ..
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://deploy.zip
        aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --environment "Variables={LINE_NOTIFY_TOKEN=${{ secrets.LINE_NOTIFY_TOKEN }}}"
